# Generated by Django 4.2.8 on 2026-04-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_globalsafety_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
