# Generated by Django 4.2.8 on 2026-04-02 17:42

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_organizationinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationinvite',
            name='expires_at',
            field=models.DateTimeField(default=accounts.models.default_expiry),
        ),
    ]
