# Generated by Django 4.2.8 on 2026-04-07 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_instancepricing'),
        ('accounts', '0007_organizationinvite_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCPAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('project_id', models.CharField(max_length=255)),
                ('service_account_json', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cloud_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gcp', to='cloud.cloudaccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gcp_accounts', to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='AzureAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tenant_id', models.CharField(max_length=255)),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(max_length=255)),
                ('subscription_id', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cloud_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='azure', to='cloud.cloudaccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='azure_accounts', to='accounts.organization')),
            ],
        ),
    ]
