# Generated by Django 4.2.8 on 2026-05-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_gcpaccount_azureaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awsaccount',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
