apiVersion: v1
kind: Service

metadata:

  name: backend-service

  namespace: autopilot

spec:

  selector:

    app: autopilot-backend

  type: ClusterIP

  ports:

  - name: http

    port: 80

    targetPort: 8000