apiVersion: v1
kind: ConfigMap

metadata:
  name: autopilot-config
  namespace: autopilot

data:
  DJANGO_SETTINGS_MODULE: config.settings

  REDIS_HOST: redis-service
  REDIS_PORT: "6379"

  DATABASE_HOST: autopilot-db-v2.c50acysmivkc.eu-north-1.rds.amazonaws.com
  DATABASE_PORT: "5430"
  DATABASE_NAME: autopilot_db

  CELERY_BROKER_URL: redis://redis-service:6379/0
  CELERY_RESULT_BACKEND: redis://redis-service:6379/0

  PYTHONUNBUFFERED: "1"