apiVersion: v1
kind: Secret

metadata:
  name: autopilot-secret
  namespace: autopilot

type: Opaque

stringData:

  DATABASE_USER: autopilot_user

  DATABASE_PASSWORD: Deeny!442

  DJANGO_SECRET_KEY: django-insecure-uky^g#)p%ew2ui$z0w!+-)ny_*j(8-oj@w4njz@@won8mb^r!*
