# Generated by Django 4.2.8 on 2026-06-07 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionexecution',
            name='action_plan',
        ),
        migrations.AddField(
            model_name='actionexecution',
            name='optimization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='actions.optimizationplan'),
        ),
    ]
