# Generated by Django 4.2.8 on 2026-06-07 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_remove_actionexecution_action_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionexecution',
            name='optimization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='actions.optimizationplan'),
        ),
    ]
