# Generated by Django 4.2.8 on 2026-06-07 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_alter_actionexecution_optimization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optimizationplan',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'PLANNED'), ('APPROVED', 'APPROVED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED'), ('REJECTED', 'REJECTED')], default='PLANNED', max_length=20),
        ),
    ]
