# Generated by Django 4.2.8 on 2026-05-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_instancepricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudaccount',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cloudaccount',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cloudaccount',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('connected', 'Connected'), ('failed', 'Failed'), ('disabled', 'Disabled')], default='pending', max_length=20),
        ),
    ]
