# Generated by Django 4.2.8 on 2026-06-03 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0003_cloudaccount_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudaccount',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
