# Generated by Django 4.2.8 on 2026-06-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsevent',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
