# Generated by Django 4.2.8 on 2026-06-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_savingsevent_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='costsnapshot',
            name='usage_quantity',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
