# Generated by Django 4.2.8 on 2026-03-14 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_instancepricing'),
        ('accounts', '0004_globalsafety_organization'),
        ('ai_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLearning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, unique=True)),
                ('executions', models.IntegerField(default=0)),
                ('total_reward', models.FloatField(default=0)),
                ('avg_reward', models.FloatField(default=0)),
                ('exploration_rate', models.FloatField(default=0.1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActionOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.CharField(max_length=255)),
                ('action_type', models.CharField(max_length=50)),
                ('before_state', models.JSONField()),
                ('after_state', models.JSONField(blank=True, null=True)),
                ('estimated_savings', models.FloatField(default=0)),
                ('success', models.BooleanField(default=False)),
                ('execution_time_seconds', models.FloatField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AutopilotRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('plans_generated', models.IntegerField(default=0)),
                ('plans_executed', models.IntegerField(default=0)),
                ('status', models.CharField(default='running', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OptimizationOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_account_id', models.UUIDField()),
                ('resource_type', models.CharField(max_length=100)),
                ('resource_id', models.CharField(max_length=200)),
                ('action_type', models.CharField(max_length=100)),
                ('cpu_utilization', models.FloatField(blank=True, null=True)),
                ('memory_utilization', models.FloatField(blank=True, null=True)),
                ('estimated_savings', models.FloatField(default=0)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('converted_to_plan', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OptimizationStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('action_type', models.CharField(max_length=100)),
                ('resource_type', models.CharField(max_length=100)),
                ('parameters', models.JSONField(default=dict)),
                ('success_rate', models.FloatField(default=0)),
                ('avg_reward', models.FloatField(default=0)),
                ('executions', models.IntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.CharField(db_index=True, max_length=255)),
                ('resource_type', models.CharField(db_index=True, max_length=100)),
                ('cpu_avg', models.FloatField(null=True)),
                ('memory_avg', models.FloatField(null=True)),
                ('network_avg', models.FloatField(null=True)),
                ('estimated_monthly_savings', models.FloatField(default=0)),
                ('risk_score', models.FloatField(null=True)),
                ('execution_time_seconds', models.IntegerField(default=0)),
                ('action_success', models.BooleanField(null=True)),
                ('feature_version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('resource_type', models.CharField(max_length=100)),
                ('predicted_savings', models.FloatField()),
                ('predicted_risk', models.FloatField()),
                ('confidence', models.FloatField(default=0.5)),
                ('parameters', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ResourceUsage',
        ),
        migrations.AddIndex(
            model_name='resourcefeature',
            index=models.Index(fields=['resource_id'], name='ai_engine_r_resourc_49c3db_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcefeature',
            index=models.Index(fields=['resource_type'], name='ai_engine_r_resourc_3c9c22_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcefeature',
            index=models.Index(fields=['created_at'], name='ai_engine_r_created_0aa974_idx'),
        ),
        migrations.AddField(
            model_name='autopilotrun',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='actionoutcome',
            name='cloud_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_outcomes', to='cloud.cloudaccount'),
        ),
        migrations.AddField(
            model_name='actionoutcome',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_outcomes', to='accounts.organization'),
        ),
        migrations.AddIndex(
            model_name='autopilotrun',
            index=models.Index(fields=['organization', 'started_at'], name='ai_engine_a_organiz_7f5df5_idx'),
        ),
        migrations.AddIndex(
            model_name='actionoutcome',
            index=models.Index(fields=['resource_type'], name='ai_engine_a_resourc_5a8f48_idx'),
        ),
        migrations.AddIndex(
            model_name='actionoutcome',
            index=models.Index(fields=['action_type'], name='ai_engine_a_action__3f0cc1_idx'),
        ),
    ]
