# Generated by Django 4.2.8 on 2026-06-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0002_actionlearning_actionoutcome_autopilotrun_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPUMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workload_id', models.CharField(db_index=True, max_length=128)),
                ('resource_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('provider', models.CharField(blank=True, default='', max_length=32)),
                ('region', models.CharField(blank=True, default='', max_length=64)),
                ('gpu_model', models.CharField(blank=True, default='', max_length=64)),
                ('utilization', models.FloatField()),
                ('mem_used', models.IntegerField()),
                ('mem_total', models.IntegerField()),
                ('power_draw', models.FloatField(default=0)),
                ('temperature', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['workload_id', 'timestamp'], name='ai_engine_g_workloa_55c868_idx'), models.Index(fields=['resource_id', 'timestamp'], name='ai_engine_g_resourc_fc5e75_idx')],
            },
        ),
    ]
